option(BLACKBASE_ENABLE_DISASSEMBLER "Enable disassembler support" OFF)
if (BLACKBASE_ENABLE_DISASSEMBLER)
    add_compile_definitions(BLACKBASE_ENABLE_DISASSEMBLER)

    option(BLACKBASE_USE_ZYDIS "Use Zydis for disassembly" ON)
    option(BLACKBASE_USE_UD2 "Use Udis86 for disassembly" OFF)

    if (BLACKBASE_USE_ZYDIS AND BLACKBASE_USE_UD2)
        message(FATAL_ERROR "Cannot use both Zydis and Udis86 for disassembly. Please choose one.")
    elseif (NOT BLACKBASE_USE_ZYDIS AND NOT BLACKBASE_USE_UD2)
        message(FATAL_ERROR "Disassembler support is enabled, but neither Zydis nor Udis86 is selected. Please choose one.")
    elseif (BLACKBASE_USE_ZYDIS)
        add_compile_definitions(BLACKBASE_USE_ZYDIS)
        include(cmake/zydis.cmake)
    elseif (BLACKBASE_USE_UD2)
        add_compile_definitions(BLACKBASE_USE_UD2)
        include(cmake/udis86.cmake)
    endif()
endif()